### ISSUE TITLE
database file

### ISSUE THREAD

**Issue by ksoft1** [cfabela/medicine_tracker#1]
hi, i downloaded your app, it seems there is no database file.

**Comment by cfabela** [comment]
Hi @ksoftone  please check the folowwing file, you can add a breakpoint to see if the database is being created.

Also on ios you can printout the url from the datagbase is being installed and test it using a tool like SqliteStudio

**Comment by ksoft1** [comment]
where is the file?

**Comment by cfabela** [comment]
medicine_tracker/MedicineTracker/MedicineTracker/Database/Database.cs
